# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20160407_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='college_id',
        ),
    ]
